---
- name: Copy and Extract setup bundle for AAP containerised 3Gb
  hosts: all
  # become: true
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: "{{ setup }}"
        dest: "{{ hostfolder }}"
        mode: "0644"

    - name: Extract archive
      ansible.builtin.unarchive:
        src: "{{ hostfolder }}/{{ setup }}"
        dest: "{{ hostfolder }}"
        remote_src: true

    - name: Delete file
      ansible.builtin.file:
        path: "{{ hostfolder }}/{{ setup }}"
        state: absent
