---
- name: Registering machine and attaching 'Employee SKU'
  hosts: node1
  become: true
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: Registering machine and attaching 'Employee SKU'
      community.general.redhat_subscription:
        state: present
        username: "{{ rh_username }}"
        password: "{{ rh_password }}"
        pool_ids: "{{ subscription_pool_id }}"
